### PR TITLE
Added support for accessing window.location

### PR DESCRIPTION
**Pull request by AlphaRoy14**
I've added a method for accessing the window.location object. Let me know if any changes are required.

### CODE REVIEW

**Comment by rasjani** [comment]
build failures are due to some changes from my side and i'll take a look into those later.. But.

I already added similar thing for "navigator" stuff in here: https://github.com/rasjani/robotframework-seleniumtestability/commit/2899d01a320aa2a409ce3a51f68a4b38e75f2ce7

Similarry, location could have also keywords for fetching:

1. hash
1. host
1. hostname
1. href
1. origin 
1. port
1. protocol
1. search 

Similar approach as with the navigator could be used ..

**Comment by AlphaRoy14** [comment]
I have made the changes by adding methods to fetch the different keywords. Please let me know if further changes are required.

**Comment by rasjani** [comment]
Looks excellent - Thanks.  Will merge after ive cleaned up the windows test failures and done some experiments.

**Comment by rasjani** [comment]
merged manually. Thank you once again.

**Pull request closed without merging**
